CREATE TABLE IF NOT EXISTS linked_events (
  id VARCHAR(20) NOT NULL,
  server VARCHAR(20) NOT NULL,
  parentid VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);
//
CREATE TABLE IF NOT EXISTS teamspeak_tokens (
  id VARCHAR(20) NOT NULL,
  token TINYTEXT NOT NULL,
  used BOOLEAN NOT NULL DEFAULT 0,
  usedby TINYTEXT,
  PRIMARY KEY (id)
);
